stages:
    - setup

Setup:
    stage: setup
    script:
        - unset http_proxy && unset https_proxy && unset HTTP_PROXY && unset HTTPS_PROXY
        - /bin/bash setup.sh
    tags:
        - shell_frontend
    when: manual
